language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm version
jobs:
  include:
    - stage: Compile
      script: npm run build:with-tests
      compile:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Tests
      script: npm test
      test:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Clean Compile
      script: npm run clean && npm run build
      clean-compile:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Deployment
      node_js: "7"
      script: npm run deploy
      deploy:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
stages:
  - Compile
  - Test
  - Clean Compile
  - Deployment