language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm version
script:
  - npm run travis

jobs:
  include:
    - stage: npm release
      node_js: "7"
      script: npm publish
      deploy:
        provider: npm
        email: "trishantpahwa@gmail.com"
        api_key: "d1289530-81b3-4854-8bbb-05904085f451"
        on:
          tags: true
          branch: master