language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm version
before_script:
  - npm prune
jobs:
  include:
    - stage: Compile
      script: npm run build:with-tests
      compile:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Tests
      script: npm test
      tests:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Deployment
      script: npm run build
      deploy:
        provider: npm
        email: "trishantpahwa@gmail.com"
        api_key: "6c7a9eee-9146-4221-aad8-cc0c8d39e55c"
        on:
          tags: true
          branch: master
stages:
  - Compile
  - Tests
  - Deployment
after_success:
  - npm run semantic-release