language: node_js
node_js:
  - 7
before_install:
  - npm version
script:
  - npm run travis
deploy:
  - provider: npm
  - email: "trishantpahwa@gmail.com"
  - api_key: "d1289530-81b3-4854-8bbb-05904085f451"
  - script: "npm publish"
  - on:
    tags: true
    branch: production