language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm version
script:
  - npm run travis

jobs:
  include:
    - stage: npm release
      node_js: "7"
      script: echo "Deploying to npm..."
      deploy:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: release