language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm version
before_script:
  - npm prune
jobs:
  include:
    - stage: Compile
      script: npm run build:with-tests
      compile:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Tests
      script: npm run build:with-tests && npm test
      test:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Clean Compile
      script: npm run build
      clean-compile:
        provider: npm
        email: "trishantpahwa@gmail.com"
        on:
          tags: true
          branch: master
    - stage: Deployment
      node_js: "7"
      script: npm run build && echo "Continue to deployment."
      deploy:
        provider: npm
        email: "trishantpahwa@gmail.com"
        api_key: $NPM_TOKEN
        on:
          tags: true
          branch: master
stages:
  - Compile
  - Tests
  - Clean Compile
  - Deployment